package com.example;

import fr.example.FrenchHello;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        String name = "Dima";
        FrenchHello hiFr = new FrenchHello();
        System.out.println(hiFr.hello(name));
    }
}
