/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import fr.example.FrenchHello;
import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class FrenchHelloTest {

    @Test public void testSomeLibraryMethod() {
        FrenchHello hi = new FrenchHello();
        Assert.assertEquals("French", hi.getLanguage());
    }
}
