package com.dmtavt.utils;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;

public class TextUtilsTest {
    @Test public void testSomeLibraryMethod() {
        Assert.assertNotNull(TextUtils.someLibraryMethod());
    }
}
