package fr.example;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class FrenchHello implements com.example.api.ILib1Methods {

    public String whoAmI() {
        return FrenchHello.class.getCanonicalName();
    }

    @Override
    public String hello(String name) {
        return "Bonjour " + name;
    }

    @Override
    public String getLanguage() {
        return "French";
    }
}
