package com.dmtavt.utils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public final class TextUtils {
    private TextUtils() {}

    public static String someLibraryMethod() {
        return TextUtils.class.getCanonicalName() + ".someLibraryMethod()";
    }
}
